//! Embeds the vendored skills (`daemon/skills/<id>/**`, see `skills/README.md`) into the binary. It writes
//! `OUT_DIR/bundled_skills.rs`, which `src/skills.rs` includes:
//! `pub static SKILLS: &[(&str, &[(&str, &[u8])])]`, one entry per skill folder: its id, then every file in it
//! (path relative to the folder, `/` separators, bytes from `include_bytes!`).

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-changed=skills");
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    let root = manifest.join("skills");

    let mut ids: Vec<String> = Vec::new();
    for entry in sorted_entries(&root) {
        // Only folders are skills: README.md next to them is not one.
        let file_type = entry.file_type().expect("readable entry");
        if file_type.is_dir() {
            ids.push(entry.file_name().into_string().expect("skill folder names are UTF-8"));
        }
    }

    let mut code = String::from("// Generated by daemon/build.rs from daemon/skills. Do not edit.\n");
    let mut table = String::new();
    for (n, id) in ids.iter().enumerate() {
        let dir = root.join(id);
        let mut files = Vec::new();
        walk(&dir, &dir, &mut files);
        files.sort();
        code.push_str(&format!("static FILES_{n}: &[(&str, &[u8])] = &[\n"));
        for rel in &files {
            let abs = dir.join(rel);
            code.push_str(&format!(
                "    ({rel:?}, include_bytes!({:?})),\n",
                abs.display().to_string()
            ));
        }
        code.push_str("];\n");
        table.push_str(&format!("    ({id:?}, FILES_{n}),\n"));
    }
    code.push_str("/// Every vendored skill: its folder name and its files.\n");
    code.push_str("#[allow(clippy::type_complexity)] // the type is the one spelled out in build.rs\n");
    code.push_str("pub static SKILLS: &[(&str, &[(&str, &[u8])])] = &[\n");
    code.push_str(&table);
    code.push_str("];\n");

    fs::write(out_dir.join("bundled_skills.rs"), code).expect("write bundled_skills.rs");
}

fn sorted_entries(dir: &Path) -> Vec<fs::DirEntry> {
    let mut entries: Vec<fs::DirEntry> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", dir.display()))
        .map(|e| e.expect("readable directory entry"))
        .collect();
    entries.sort_by_key(|e| e.file_name());
    entries
}

/// Every file under `dir`, relative to `base`. A symlink in a vendored skill is a build error: the copy must be real.
fn walk(dir: &Path, base: &Path, out: &mut Vec<String>) {
    for entry in sorted_entries(dir) {
        let path = entry.path();
        let file_type = entry.file_type().expect("readable entry");
        if file_type.is_symlink() {
            panic!("{} is a symlink; vendored skills must be plain files", path.display());
        }
        if file_type.is_dir() {
            walk(&path, base, out);
        } else {
            let rel = path.strip_prefix(base).expect("under the skill folder");
            let rel = rel.to_str().expect("skill file names are UTF-8").replace('\\', "/");
            out.push(rel);
        }
    }
}
