#!/usr/bin/env python3
"""Generate platform string resources from i18n/*.json.

  python3 i18n/build.py           validate, then write the generated files
  python3 i18n/build.py --check   validate, then fail if the generated files are stale

Apple output is classic per-language resources (Resources/<code>.lproj/Localizable.strings
for plain keys, Localizable.stringsdict for plurals), not .xcstrings: SwiftPM copies these
on every Xcode version, while older toolchains do not compile .xcstrings in packages.

Standard library only. All paths are resolved from this script's location, so the
script works from any working directory.
"""

import json
import plistlib
import re
import sys
from pathlib import Path

I18N_DIR = Path(__file__).resolve().parent
REPO_ROOT = I18N_DIR.parent
BANDITO_L10N = REPO_ROOT / "apps/mac/BanditoKit/Sources/BanditoL10n"
RESOURCES_DIR = BANDITO_L10N / "Resources"
STRINGS_FILE = "Localizable.strings"
STRINGSDICT_FILE = "Localizable.stringsdict"
SWIFT_PATH = BANDITO_L10N / "L10n.swift"

REFERENCE = "en"
LANGUAGES_FILE = "languages.json"
PLURAL_CATEGORIES = ("zero", "one", "two", "few", "many", "other")
PLACEHOLDER_RE = re.compile(r"\{([A-Za-z][A-Za-z0-9]*)\}")
KEY_SEGMENT_RE = re.compile(r"[A-Za-z][A-Za-z0-9]*")
COUNT = "count"
ROOT_RESERVED = frozenset({"bundle", "languages", "locale", "tr", "LocaleCache"})
HEADER = "// Generated by i18n/build.py from i18n/*.json — do not edit."
STRINGS_HEADER = "/* Generated by i18n/build.py from i18n/*.json — do not edit. */"

SWIFT_KEYWORDS = frozenset(
    """
    associatedtype class deinit enum extension fileprivate func import init inout
    internal let open operator private precedencegroup protocol public rethrows
    static struct subscript typealias var break case catch continue default defer
    do else fallthrough for guard if in repeat return throw switch where while
    Any as await false is nil self Self super throws true try Type Protocol
    """.split()
)


def _reject_duplicate_keys(label, errors):
    def hook(pairs):
        obj = {}
        for key, value in pairs:
            if key in obj:
                errors.append(f"{label}: {key}: duplicate key")
            obj[key] = value
        return obj

    return hook


def load_json(path, label, errors):
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        errors.append(f"{label}: cannot read {path.name}: {exc.strerror}")
        return None
    try:
        return json.loads(text, object_pairs_hook=_reject_duplicate_keys(label, errors))
    except json.JSONDecodeError as exc:
        errors.append(f"{label}: invalid JSON in {path.name}: {exc}")
        return None


def load_languages(errors):
    raw = load_json(I18N_DIR / LANGUAGES_FILE, LANGUAGES_FILE, errors)
    if raw is None:
        return []
    if not isinstance(raw, list):
        errors.append(f"{LANGUAGES_FILE}: must be a JSON array")
        return []
    entries = []
    codes = set()
    for entry in raw:
        fields_ok = isinstance(entry, dict) and all(
            isinstance(entry.get(field), str) and entry.get(field).strip()
            for field in ("code", "name", "native")
        )
        if not fields_ok:
            errors.append(f"{LANGUAGES_FILE}: each entry needs non-empty string fields code, name, native")
            continue
        if entry["code"] in codes:
            errors.append(f"{LANGUAGES_FILE}: {entry['code']}: listed more than once")
            continue
        codes.add(entry["code"])
        entries.append(entry)
    if REFERENCE not in codes:
        errors.append(f"{LANGUAGES_FILE}: must list \"{REFERENCE}\" (the reference language)")
    return entries


def kind_of(value):
    return "a string" if isinstance(value, str) else "a plural object"


def check_shape(label, key, value, errors):
    """A value is a non-empty string, or a plural object with CLDR categories and "other"."""
    if isinstance(value, str):
        if not value.strip():
            errors.append(f"{label}: {key}: empty value")
            return False
        return True
    if isinstance(value, dict):
        unknown = [c for c in value if c not in PLURAL_CATEGORIES]
        if unknown:
            errors.append(
                f"{label}: {key}: unknown plural category {', '.join(unknown)} "
                f"(allowed: {', '.join(PLURAL_CATEGORIES)})"
            )
            return False
        if "other" not in value:
            errors.append(f"{label}: {key}: plural object must have an \"other\" form")
            return False
        for category, text in value.items():
            if not isinstance(text, str) or not text.strip():
                errors.append(f"{label}: {key}: plural \"{category}\" must be a non-empty string")
                return False
        return True
    errors.append(f"{label}: {key}: value must be a string or a plural object")
    return False


def texts_of(value):
    if isinstance(value, str):
        return [value]
    return [value[c] for c in PLURAL_CATEGORIES if c in value]


def placeholder_names(value):
    return {name for text in texts_of(value) for name in PLACEHOLDER_RE.findall(text)}


def placeholder_order(value):
    """Argument order: first appearance in English; for plurals "other" decides, the rest follow."""
    if isinstance(value, str):
        texts = [value]
    else:
        texts = [value["other"]] + [value[c] for c in PLURAL_CATEGORIES if c in value and c != "other"]
    order = []
    for text in texts:
        for name in PLACEHOLDER_RE.findall(text):
            if name not in order:
                order.append(name)
    return order


def check_translation(code, key, ref_value, value, errors):
    if isinstance(ref_value, str) != isinstance(value, str):
        errors.append(f"{code}: {key}: must be {kind_of(ref_value)} as in English, got {kind_of(value)}")
        return
    want = placeholder_names(ref_value)
    have = placeholder_names(value)
    if want != have:
        parts = []
        if want - have:
            parts.append("missing " + ", ".join("{" + n + "}" for n in sorted(want - have)))
        if have - want:
            parts.append("not in English " + ", ".join("{" + n + "}" for n in sorted(have - want)))
        errors.append(f"{code}: {key}: placeholders differ from English ({'; '.join(parts)})")


def to_format(text, order):
    """Placeholders become positional specifiers; a literal % is escaped as %%."""
    out = []
    pos = 0
    for match in PLACEHOLDER_RE.finditer(text):
        out.append(text[pos:match.start()].replace("%", "%%"))
        name = match.group(1)
        position = order.index(name) + 1
        out.append(f"%{position}$lld" if name == COUNT else f"%{position}$@")
        pos = match.end()
    out.append(text[pos:].replace("%", "%%"))
    return "".join(out)


def strings_escape(text):
    """Escape for a quoted value in a .strings file."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def plural_rule(value, order):
    """One stringsdict entry. The count argument selects the category; the category text
    is formatted with the full argument list, so its positional specifiers stay valid."""
    count_position = order.index(COUNT) + 1
    categories = {category: to_format(text, order) for category, text in value.items()}
    return {
        "NSStringLocalizedFormatKey": f"%{count_position}$#@value@",
        "value": {
            "NSStringFormatSpecTypeKey": "NSStringPluralRuleType",
            "NSStringFormatValueTypeKey": "lld",
            **categories,
        },
    }


def build_lproj(translations, reference):
    """Return (Localizable.strings bytes, Localizable.stringsdict bytes) for one language.
    Only keys present in the language are written; the rest fall back to English."""
    lines = [STRINGS_HEADER]
    plurals = {}
    for key in sorted(translations):
        value = translations[key]
        order = placeholder_order(reference[key])
        if isinstance(value, str):
            lines.append(f'"{key}" = "{strings_escape(to_format(value, order))}";')
        else:
            plurals[key] = plural_rule(value, order)
    strings_text = "\n".join(lines) + "\n"
    stringsdict = plistlib.dumps(plurals, fmt=plistlib.FMT_XML, sort_keys=True)
    return strings_text.encode("utf-8"), stringsdict


class Node:
    def __init__(self):
        self.leaves = {}  # segment -> full key
        self.children = {}  # segment -> Node


def build_tree(keys):
    root = Node()
    for key in keys:
        *path, leaf = key.split(".")
        node = root
        for segment in path:
            node = node.children.setdefault(segment, Node())
        node.leaves[leaf] = key
    return root


def leaf_name(segment):
    return segment[0].lower() + segment[1:]


def type_name(segment):
    return segment[0].upper() + segment[1:]


def swift_ident(name):
    return f"`{name}`" if name in SWIFT_KEYWORDS else name


def swift_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def check_swift_names(root, errors):
    if set(root.leaves) & ROOT_RESERVED:
        clash = ", ".join(sorted(set(root.leaves) & ROOT_RESERVED))
        errors.append(f"{REFERENCE}: top-level key(s) {clash} clash with L10n helpers")

    def walk(node, where):
        names = [leaf_name(s) for s in node.leaves]
        duplicates = {n for n in names if names.count(n) > 1}
        types = [type_name(s) for s in node.children]
        duplicates |= {n for n in types if types.count(n) > 1}
        for name in sorted(duplicates):
            errors.append(f"{REFERENCE}: {where or 'root'}: Swift name {name} is produced twice")
        for segment, child in node.children.items():
            walk(child, f"{where}.{segment}" if where else segment)

    walk(root, "")


def emit_node(node, depth, reference, lines):
    pad = "    " * depth
    for segment in sorted(node.leaves):
        key = node.leaves[segment]
        order = placeholder_order(reference[key])
        name = swift_ident(leaf_name(segment))
        if not order:
            lines.append(f'{pad}public static var {name}: String {{ L10n.tr("{key}") }}')
            continue
        signature = ", ".join(f"{swift_ident(n)}: {'Int' if n == COUNT else 'String'}" for n in order)
        arguments = ", ".join(swift_ident(n) for n in order)
        lines.append(
            f'{pad}public static func {name}({signature}) -> String {{ L10n.tr("{key}", {arguments}) }}'
        )
    for segment in sorted(node.children):
        lines.append("")
        lines.append(f"{pad}public enum {swift_ident(type_name(segment))} {{")
        emit_node(node.children[segment], depth + 1, reference, lines)
        lines.append(f"{pad}}}")


def build_swift(entries, reference):
    lines = [
        HEADER,
        "import Foundation",
        "",
        "public enum L10n {",
        "    public static let bundle = Bundle.module",
        "",
        "    static func tr(_ key: String, _ args: CVarArg...) -> String {",
        '        let format = Bundle.module.localizedString(forKey: key, value: nil, table: "Localizable")',
        "        // Most strings take no arguments: skip formatting, only unescape the percent sign. Views read",
        "        // strings on every update, so this path has to be cheap.",
        '        if args.isEmpty { return format.contains("%%") ? format.replacingOccurrences(of: "%%", with: "%") : format }',
        "        return String(format: format, locale: locale, arguments: args)",
        "    }",
        "",
        "    /// Locale of the language the strings come from. Plural rules and number formats follow it,",
        "    /// not the system locale: a Russian UI on an English Mac still gets Russian plurals.",
        "    public static var locale: Locale {",
        '        LocaleCache.shared.locale(for: Bundle.module.preferredLocalizations.first ?? "en")',
        "    }",
        "",
        "    /// One `Locale` per language identifier: making a `Locale` for every string was a hot spot.",
        "    final class LocaleCache: @unchecked Sendable {",
        "        static let shared = LocaleCache()",
        "        private let lock = NSLock()",
        "        private var cached: (id: String, locale: Locale)?",
        "",
        "        func locale(for id: String) -> Locale {",
        "            lock.lock()",
        "            defer { lock.unlock() }",
        "            if let cached, cached.id == id { return cached.locale }",
        "            let locale = Locale(identifier: id)",
        "            cached = (id, locale)",
        "            return locale",
        "        }",
        "    }",
        "",
        "    public static let languages: [(code: String, native: String)] = [",
    ]
    for entry in entries:
        lines.append(f"        ({swift_string(entry['code'])}, {swift_string(entry['native'])}),")
    lines.append("    ]")
    emit_node(build_tree(sorted(reference)), 1, reference, lines)
    lines.append("}")
    return "\n".join(lines) + "\n"


def build():
    errors = []
    warnings = []

    entries = load_languages(errors)
    codes = [entry["code"] for entry in entries]

    for path in sorted(I18N_DIR.glob("*.json")):
        if path.name != LANGUAGES_FILE and path.stem not in codes:
            errors.append(f"i18n/{path.name}: not listed in languages.json")

    data = {}
    for code in codes:
        path = I18N_DIR / f"{code}.json"
        if not path.is_file():
            errors.append(f"{code}: missing file i18n/{code}.json")
            continue
        loaded = load_json(path, code, errors)
        if loaded is None:
            continue
        if not isinstance(loaded, dict):
            errors.append(f"{code}: file must contain a JSON object")
            continue
        data[code] = loaded

    if REFERENCE not in data:
        return errors, warnings, None
    reference = data[REFERENCE]

    for key in reference:
        if not all(KEY_SEGMENT_RE.fullmatch(s) for s in key.split(".")):
            errors.append(
                f"{REFERENCE}: {key}: key segments must be letters and digits, "
                "camelCase (they become Swift identifiers)"
            )
        if isinstance(reference[key], dict) and COUNT not in placeholder_names(reference[key]):
            errors.append(f"{REFERENCE}: {key}: a plural must use the {{{COUNT}}} placeholder")

    for code in codes:
        if code not in data:
            continue
        translations = data[code]
        for key, value in translations.items():
            if key not in reference:
                errors.append(f"{code}: {key}: unknown key (not in en.json)")
                continue
            if not check_shape(code, key, value, errors) or code == REFERENCE:
                continue
            check_translation(code, key, reference[key], value, errors)
        if code != REFERENCE:
            missing = [key for key in reference if key not in translations]
            if missing:
                warnings.append(f"{code}: {len(missing)} missing (falls back to English)")
                warnings.append("  " + ", ".join(missing))

    check_swift_names(build_tree(sorted(reference)), errors)

    if errors:
        return errors, warnings, None

    outputs = {SWIFT_PATH: build_swift(entries, reference).encode("utf-8")}
    for code in codes:
        strings_bytes, stringsdict_bytes = build_lproj(data[code], reference)
        lproj = RESOURCES_DIR / f"{code}.lproj"
        outputs[lproj / STRINGS_FILE] = strings_bytes
        outputs[lproj / STRINGSDICT_FILE] = stringsdict_bytes
    return errors, warnings, outputs


def main(argv):
    if any(arg != "--check" for arg in argv):
        print("usage: python3 i18n/build.py [--check]", file=sys.stderr)
        return 2
    check = "--check" in argv

    errors, warnings, outputs = build()
    for line in warnings:
        print(line, file=sys.stderr)
    if errors:
        print(f"i18n validation failed ({len(errors)} problem(s)):", file=sys.stderr)
        for line in errors:
            print(f"  {line}", file=sys.stderr)
        return 1

    if check:
        stale = [p for p, content in outputs.items() if not p.is_file() or p.read_bytes() != content]
        if stale:
            for path in stale:
                print(f"  stale: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("generated files are out of date: run python3 i18n/build.py", file=sys.stderr)
            return 1
        print("i18n: OK, generated files are up to date")
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
