// Generated by i18n/build.py from i18n/*.json — do not edit.
import Foundation

public enum L10n {
    public static let bundle = Bundle.module

    static func tr(_ key: String, _ args: CVarArg...) -> String {
        let format = Bundle.module.localizedString(forKey: key, value: nil, table: "Localizable")
        return String(format: format, locale: Locale.current, arguments: args)
    }

    public static let languages: [(code: String, native: String)] = [
        ("en", "English"),
        ("ru", "Русский"),
        ("ja", "日本語"),
        ("zh-Hans", "简体中文"),
        ("ko", "한국어"),
        ("es", "Español"),
        ("pt-BR", "Português (Brasil)"),
        ("de", "Deutsch"),
        ("fr", "Français"),
    ]

    public enum Agent {

        public enum Delete {
            public static func confirm(name: String) -> String { L10n.tr("agent.delete.confirm", name) }
        }

        public enum Menu {
            public static var copyId: String { L10n.tr("agent.menu.copyId") }
            public static var delete: String { L10n.tr("agent.menu.delete") }
            public static var hide: String { L10n.tr("agent.menu.hide") }
            public static var markUnread: String { L10n.tr("agent.menu.markUnread") }
            public static var pause: String { L10n.tr("agent.menu.pause") }
            public static var pin: String { L10n.tr("agent.menu.pin") }
            public static var resume: String { L10n.tr("agent.menu.resume") }
            public static var unpin: String { L10n.tr("agent.menu.unpin") }
        }
    }

    public enum AgentSheet {
        public static var approvals: String { L10n.tr("agentSheet.approvals") }
        public static var avatar: String { L10n.tr("agentSheet.avatar") }
        public static var cancel: String { L10n.tr("agentSheet.cancel") }
        public static var create: String { L10n.tr("agentSheet.create") }
        public static var folder: String { L10n.tr("agentSheet.folder") }
        public static var instructions: String { L10n.tr("agentSheet.instructions") }
        public static var model: String { L10n.tr("agentSheet.model") }
        public static var modelDefault: String { L10n.tr("agentSheet.modelDefault") }
        public static var name: String { L10n.tr("agentSheet.name") }
        public static var role: String { L10n.tr("agentSheet.role") }
        public static var rolePlaceholder: String { L10n.tr("agentSheet.rolePlaceholder") }
        public static var runtime: String { L10n.tr("agentSheet.runtime") }
        public static func runtimeLogin(runtime: String, server: String, command: String) -> String { L10n.tr("agentSheet.runtimeLogin", runtime, server, command) }
        public static func runtimeMissing(runtime: String, server: String) -> String { L10n.tr("agentSheet.runtimeMissing", runtime, server) }
        public static var title: String { L10n.tr("agentSheet.title") }
    }

    public enum App {
        public static var name: String { L10n.tr("app.name") }
    }

    public enum Approval {
        public static var always: String { L10n.tr("approval.always") }
        public static var approve: String { L10n.tr("approval.approve") }
        public static func approvedByYou(time: String) -> String { L10n.tr("approval.approvedByYou", time) }
        public static var deniedByPolicy: String { L10n.tr("approval.deniedByPolicy") }
        public static func deniedByYou(time: String) -> String { L10n.tr("approval.deniedByYou", time) }
        public static var deny: String { L10n.tr("approval.deny") }
        public static var expired: String { L10n.tr("approval.expired") }
        public static var needsYou: String { L10n.tr("approval.needsYou") }
        public static func wants(name: String) -> String { L10n.tr("approval.wants", name) }
    }

    public enum ApprovalMode {
        public static var always: String { L10n.tr("approvalMode.always") }
        public static var never: String { L10n.tr("approvalMode.never") }
        public static var risky: String { L10n.tr("approvalMode.risky") }
    }

    public enum Avatar {
        public static var generate: String { L10n.tr("avatar.generate") }
        public static var presets: String { L10n.tr("avatar.presets") }
        public static var reset: String { L10n.tr("avatar.reset") }
        public static var set: String { L10n.tr("avatar.set") }
        public static var upload: String { L10n.tr("avatar.upload") }
    }

    public enum Banner {
        public static func limit(time: String) -> String { L10n.tr("banner.limit", time) }
        public static func notLoggedIn(runtime: String, server: String, command: String) -> String { L10n.tr("banner.notLoggedIn", runtime, server, command) }
        public static func offline(server: String) -> String { L10n.tr("banner.offline", server) }
        public static var retry: String { L10n.tr("banner.retry") }
    }

    public enum Error {
        public static func disconnected(server: String) -> String { L10n.tr("error.disconnected", server) }
        public static func generic(message: String) -> String { L10n.tr("error.generic", message) }
    }

    public enum Inspector {
        public static var addSchedule: String { L10n.tr("inspector.addSchedule") }
        public static var details: String { L10n.tr("inspector.details") }
        public static var library: String { L10n.tr("inspector.library") }
        public static func nextRun(time: String) -> String { L10n.tr("inspector.nextRun", time) }
        public static func resets(time: String) -> String { L10n.tr("inspector.resets", time) }
        public static var rules: String { L10n.tr("inspector.rules") }
        public static var runNow: String { L10n.tr("inspector.runNow") }
        public static var schedules: String { L10n.tr("inspector.schedules") }
        public static var server: String { L10n.tr("inspector.server") }
        public static var usage: String { L10n.tr("inspector.usage") }

        public enum Window {
            public static var fiveHour: String { L10n.tr("inspector.window.fiveHour") }
            public static var sevenDay: String { L10n.tr("inspector.window.sevenDay") }
        }
    }

    public enum Menubar {
        public static func needsYou(count: Int) -> String { L10n.tr("menubar.needsYou", count) }
        public static var `open`: String { L10n.tr("menubar.open") }
        public static var pauseAll: String { L10n.tr("menubar.pauseAll") }
    }

    public enum New {
        public static var agent: String { L10n.tr("new.agent") }
        public static var channel: String { L10n.tr("new.channel") }
        public static var placeholder: String { L10n.tr("new.placeholder") }
        public static var to: String { L10n.tr("new.to") }
    }

    public enum Notification {
        public static func approval(name: String) -> String { L10n.tr("notification.approval", name) }
        public static func finished(name: String) -> String { L10n.tr("notification.finished", name) }
    }

    public enum Profile {
        public static var addServer: String { L10n.tr("profile.addServer") }
        public static var getIphone: String { L10n.tr("profile.getIphone") }
        public static var help: String { L10n.tr("profile.help") }
        public static var settings: String { L10n.tr("profile.settings") }
        public static var signOut: String { L10n.tr("profile.signOut") }
    }

    public enum Runtime {
        public static var api: String { L10n.tr("runtime.api") }
        public static var claude: String { L10n.tr("runtime.claude") }
        public static var codex: String { L10n.tr("runtime.codex") }
        public static var grok: String { L10n.tr("runtime.grok") }
    }

    public enum Search {
        public static var noResults: String { L10n.tr("search.noResults") }
        public static var placeholder: String { L10n.tr("search.placeholder") }
    }

    public enum Server {

        public enum Add {
            public static var code: String { L10n.tr("server.add.code") }
            public static var codeHint: String { L10n.tr("server.add.codeHint") }
            public static var connect: String { L10n.tr("server.add.connect") }
            public static var connecting: String { L10n.tr("server.add.connecting") }
            public static var direct: String { L10n.tr("server.add.direct") }
            public static func done(server: String) -> String { L10n.tr("server.add.done", server) }
            public static var host: String { L10n.tr("server.add.host") }
            public static var install: String { L10n.tr("server.add.install") }
            public static var port: String { L10n.tr("server.add.port") }
            public static var ssh: String { L10n.tr("server.add.ssh") }
            public static var tailscale: String { L10n.tr("server.add.tailscale") }
            public static var thisMac: String { L10n.tr("server.add.thisMac") }
            public static var title: String { L10n.tr("server.add.title") }
            public static var url: String { L10n.tr("server.add.url") }
            public static var user: String { L10n.tr("server.add.user") }
        }

        public enum Status {
            public static var offline: String { L10n.tr("server.status.offline") }
            public static var online: String { L10n.tr("server.status.online") }
        }
    }

    public enum Settings {
        public static var approvals: String { L10n.tr("settings.approvals") }
        public static var general: String { L10n.tr("settings.general") }
        public static var language: String { L10n.tr("settings.language") }
        public static var launchAtLogin: String { L10n.tr("settings.launchAtLogin") }
        public static var menuBar: String { L10n.tr("settings.menuBar") }
        public static var notifications: String { L10n.tr("settings.notifications") }
        public static var servers: String { L10n.tr("settings.servers") }
        public static var theme: String { L10n.tr("settings.theme") }
        public static var title: String { L10n.tr("settings.title") }
        public static var updates: String { L10n.tr("settings.updates") }
        public static var usage: String { L10n.tr("settings.usage") }

        public enum Language {
            public static var system: String { L10n.tr("settings.language.system") }
        }

        public enum Rules {
            public static var action: String { L10n.tr("settings.rules.action") }
            public static var add: String { L10n.tr("settings.rules.add") }
            public static var allow: String { L10n.tr("settings.rules.allow") }
            public static var ask: String { L10n.tr("settings.rules.ask") }
            public static var behavior: String { L10n.tr("settings.rules.behavior") }
            public static var builtin: String { L10n.tr("settings.rules.builtin") }
            public static var deny: String { L10n.tr("settings.rules.deny") }
        }

        public enum Theme {
            public static var dark: String { L10n.tr("settings.theme.dark") }
            public static var light: String { L10n.tr("settings.theme.light") }
            public static var system: String { L10n.tr("settings.theme.system") }
        }

        public enum Updates {
            public static var auto: String { L10n.tr("settings.updates.auto") }
            public static var beta: String { L10n.tr("settings.updates.beta") }
            public static var channel: String { L10n.tr("settings.updates.channel") }
            public static var check: String { L10n.tr("settings.updates.check") }
            public static var daemon: String { L10n.tr("settings.updates.daemon") }
            public static var restartDaemon: String { L10n.tr("settings.updates.restartDaemon") }
            public static var stable: String { L10n.tr("settings.updates.stable") }
        }
    }

    public enum Sidebar {
        public static var agents: String { L10n.tr("sidebar.agents") }
        public static var connectApps: String { L10n.tr("sidebar.connectApps") }
        public static var empty: String { L10n.tr("sidebar.empty") }
        public static var new: String { L10n.tr("sidebar.new") }
        public static var pinned: String { L10n.tr("sidebar.pinned") }
        public static var search: String { L10n.tr("sidebar.search") }
        public static var servers: String { L10n.tr("sidebar.servers") }
    }

    public enum Status {
        public static var error: String { L10n.tr("status.error") }
        public static var idle: String { L10n.tr("status.idle") }
        public static var needsYou: String { L10n.tr("status.needsYou") }
        public static var offline: String { L10n.tr("status.offline") }
        public static var working: String { L10n.tr("status.working") }
    }

    public enum Thread {
        public static var attach: String { L10n.tr("thread.attach") }
        public static var copy: String { L10n.tr("thread.copy") }
        public static var copyMarkdown: String { L10n.tr("thread.copyMarkdown") }
        public static func messageFor(name: String) -> String { L10n.tr("thread.messageFor", name) }
        public static func messageFrom(name: String) -> String { L10n.tr("thread.messageFrom", name) }
        public static var more: String { L10n.tr("thread.more") }
        public static func placeholder(name: String) -> String { L10n.tr("thread.placeholder", name) }
        public static func ranCommands(count: Int) -> String { L10n.tr("thread.ranCommands", count) }
        public static var react: String { L10n.tr("thread.react") }
        public static var reply: String { L10n.tr("thread.reply") }
        public static var scheduledRun: String { L10n.tr("thread.scheduledRun") }
        public static var send: String { L10n.tr("thread.send") }
        public static var stop: String { L10n.tr("thread.stop") }
        public static var stopped: String { L10n.tr("thread.stopped") }
        public static var today: String { L10n.tr("thread.today") }
        public static var yesterday: String { L10n.tr("thread.yesterday") }
    }
}
